---
kind: pipeline
name: durl
clone:
  depth: 1
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: golang:1.17.2
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.42.1
  commands:
  - golangci-lint run
  volumes: *volumes

- name: fetch tags
  image: plugins/git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: remove changes
  image: plugins/git
  commands:
  # Sometimes it is failed to release by goreleaser due to changes of go.sum
  - git checkout -- .
- name: release
  image: goreleaser/goreleaser:v0.182.1
  commands:
  - goreleaser release
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes: *volumes
  when:
    event:
    - tag

- name: release/pr
  image: goreleaser/goreleaser:v0.182.1
  commands:
  - goreleaser release --snapshot
  volumes: *volumes
  when:
    event:
    - pull_request
    - push
